FROM apache/superset:latest

USER root

RUN /app/.venv/bin/python -m ensurepip --upgrade && \
    /app/.venv/bin/python -m pip install --no-cache-dir \
    psycopg2-binary \
    "databricks-sql-connector>=2.9.0,<3.0.0"

USER superset